[package]
name = "noir-single"
version = "0.1.0"
edition = "2021"

[dependencies]
noir_rs = { git = "https://github.com/visoftsolutions/noir_rs.git", branch = "latest", package = "noir_rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
